---
 output-osversion: "..\\flussi\\osversion.csv"
 output-netinfo: "..\\flussi\\netinfo.csv"
 output-product: "..\\flussi\\product.csv"
 output-uptime: "..\\flussi\\uptime.csv"
 output-logicaldisk: "..\\flussi\\logicaldisk.csv"
 db-host: ""
 db-username: ""
 db-password: ""
 db-dbname: ""